### ISSUE TITLE
Remove the JSON / PSOL radio buttons

### ISSUE THREAD

**Issue by LarryBattle** [clarkduvall/JSOL#3]
On the homepage, I think you should remove the JSOL and PSOL radio buttons since they don't update the view automatically and also they don't work.

Cool project by the way.

**Comment by clarkduvall** [comment]
Hmm, I agree that's confusing. The buttons are to tell the server whether to interpret the program as PSOL or JSOL, so they are necessary. For example, write a program in JSOL and check the PSOL button, and you'll get an error.

I would like to clean up the interface though to make that more clear. Any suggestions?

**Comment by LarryBattle** [comment]
Replace the radio buttons with the selection and eval button side by side. 
Pass additional parameters with the POST that determine the compile mode.

**Comment by clarkduvall** [comment]
The POST is already passing additional parameters (thats what the PSOL/JSOL radio buttons are for). The problem is that if a user types in arbitrary code into the box, there is no way to tell if it is PSOL or JSOL. I could try to run it as PSOL, and if I get an exception fall back to JSOL, but thats pretty hacky and will return the wrong error messages in some cases.

**Comment by LarryBattle** [comment]
Isn't JSOL valid JSON, while PSOL isn't? 

I think it would be better if you separated the two sources. Have JSOL on one side and PSOL on the other.

Anyhow it seems ok with the current version because I just now realized that the text box allows the user to parse custom JSOL/PSOL. I original thought it was only to display code.
